// src/lib/mockData.ts

import { Course } from '@/types/course';
import { File, Folder } from '@/types/file';

// Mock courses data
export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Machine Language C',
    category: 'coding',
    description: 'Learn the fundamentals of machine language and C programming.',
    instructor: 'Prof. Sarah Johnson',
    image: '/assets/images/courses/machine-language-c.jpg',
    status: 'in_progress',
    progress: 55,
    duration: '8 weeks',
    bgColor: '#3b82f6',
    level: 'intermediate',
  },
  {
    id: 'course-2',
    title: 'Machine Learning',
    category: 'coding',
    description: 'Understand the basics of machine learning algorithms and implementation.',
    instructor: 'Dr. Robert Chen',
    image: '/assets/images/courses/machine-learning.jpg',
    status: 'not_started',
    progress: 0,
    duration: '10 weeks',
    bgColor: '#6366f1',
    level: 'advanced',
  },
  {
    id: 'course-3',
    title: 'Advanced Data Structures',
    category: 'coding',
    description: 'Master complex data structures and algorithms for efficient programming.',
    instructor: 'Prof. Michael Smith',
    image: '/assets/images/courses/data-structures.jpg',
    status: 'completed',
    progress: 100,
    duration: '6 weeks',
    bgColor: '#8b5cf6',
    level: 'advanced',
  },
  {
    id: 'course-4',
    title: 'UI/UX Design Principles',
    category: 'design',
    description: 'Learn the fundamentals of user interface and user experience design.',
    instructor: 'Emma Rodriguez',
    image: '/assets/images/courses/ui-ux-design.jpg',
    status: 'in_progress',
    progress: 35,
    duration: '7 weeks',
    bgColor: '#ec4899',
    level: 'beginner',
  },
  {
    id: 'course-5',
    title: 'Calculus for Engineers',
    category: 'math',
    description: 'Essential calculus concepts for engineering and technical applications.',
    instructor: 'Dr. James Wilson',
    image: '/assets/images/courses/calculus.jpg',
    status: 'not_started',
    progress: 0,
    duration: '12 weeks',
    bgColor: '#14b8a6',
    level: 'intermediate',
  },
  {
    id: 'course-6',
    title: 'Music Theory Basics',
    category: 'music',
    description: 'Introduction to music theory, notation, and composition fundamentals.',
    instructor: 'Lisa Morrison',
    image: '/assets/images/courses/music-theory.jpg',
    status: 'not_started',
    progress: 0,
    duration: '5 weeks',
    bgColor: '#f97316',
    level: 'beginner',
  },
];

// Mock lessons data
export interface Lesson {
  id: string;
  courseId: string;
  title: string;
  description?: string;
  duration?: string;
  completed: boolean;
  type?: 'video' | 'quiz' | 'reading' | 'practice';
}

export const mockLessons: Lesson[] = [
  // Machine Language C lessons
  {
    id: 'lesson-1-1',
    courseId: 'course-1',
    title: 'Introduction to Machine Language',
    description: 'Understanding the basics of machine language and its importance.',
    duration: '20 min',
    completed: true,
    type: 'video',
  },
  {
    id: 'lesson-1-2',
    courseId: 'course-1',
    title: 'Binary and Hexadecimal Systems',
    description: 'Learn about number systems used in computer programming.',
    duration: '25 min',
    completed: true,
    type: 'reading',
  },
  {
    id: 'lesson-1-3',
    courseId: 'course-1',
    title: 'Introduction to C Programming',
    description: 'Fundamentals of C programming language.',
    duration: '30 min',
    completed: false,
    type: 'video',
  },
  {
    id: 'lesson-1-4',
    courseId: 'course-1',
    title: 'Variables and Data Types in C',
    description: 'Understanding different data types and variable declarations in C.',
    duration: '25 min',
    completed: false,
    type: 'practice',
  },
  {
    id: 'lesson-1-5',
    courseId: 'course-1',
    title: 'Control Structures',
    description: 'Learn about if-else statements, loops, and other control structures.',
    duration: '35 min',
    completed: false,
    type: 'video',
  },
  {
    id: 'lesson-1-6',
    courseId: 'course-1',
    title: 'Functions in C',
    description: 'Creating and using functions in C programming.',
    duration: '40 min',
    completed: false,
    type: 'practice',
  },
  {
    id: 'lesson-1-7',
    courseId: 'course-1',
    title: 'Mid-term Quiz',
    description: 'Test your knowledge of the concepts covered so far.',
    duration: '45 min',
    completed: false,
    type: 'quiz',
  },
  {
    id: 'lesson-1-8',
    courseId: 'course-1',
    title: 'Pointers and Memory Management',
    description: 'Understanding pointers and memory management in C.',
    duration: '50 min',
    completed: false,
    type: 'video',
  },
  
  // Machine Learning lessons
  {
    id: 'lesson-2-1',
    courseId: 'course-2',
    title: 'Introduction to Machine Learning',
    description: 'Overview of machine learning concepts and applications.',
    duration: '30 min',
    completed: false,
    type: 'video',
  },
  {
    id: 'lesson-2-2',
    courseId: 'course-2',
    title: 'Supervised vs. Unsupervised Learning',
    description: 'Understanding different learning paradigms.',
    duration: '25 min',
    completed: false,
    type: 'reading',
  },
  
  // Advanced Data Structures lessons
  {
    id: 'lesson-3-1',
    courseId: 'course-3',
    title: 'Introduction to Advanced Data Structures',
    description: 'Overview of advanced data structures and their applications.',
    duration: '20 min',
    completed: true,
    type: 'video',
  },
  {
    id: 'lesson-3-2',
    courseId: 'course-3',
    title: 'Trees and Graphs',
    description: 'Understanding tree and graph data structures.',
    duration: '35 min',
    completed: true,
    type: 'practice',
  },
  {
    id: 'lesson-3-3',
    courseId: 'course-3',
    title: 'Final Exam',
    description: 'Comprehensive test on advanced data structures.',
    duration: '60 min',
    completed: true,
    type: 'quiz',
  },
];

// Generate placeholder course thumbnail URLs
export const getCourseThumbnailUrl = (courseId: string) => {
  return `/assets/images/courses/${courseId}-thumbnail.jpg`;
};

// Mock recently viewed courses (returns IDs)
export const getMockRecentlyViewedCourses = (): string[] => {
  return ['course-1', 'course-4', 'course-3', 'course-6'];
};

// Mock folders data
export const mockFolders: Folder[] = [
  {
    id: 'folder-1',
    name: 'Documents',
    parentId: null,
    userId: 'mock-user-1',
    createdAt: '2025-02-10T12:00:00Z',
    updatedAt: '2025-02-10T12:00:00Z',
  },
  {
    id: 'folder-2',
    name: 'Images',
    parentId: null,
    userId: 'mock-user-1',
    createdAt: '2025-02-10T12:30:00Z',
    updatedAt: '2025-02-10T12:30:00Z',
  },
  {
    id: 'folder-3',
    name: 'Projects',
    parentId: null,
    userId: 'mock-user-1',
    createdAt: '2025-02-10T13:00:00Z',
    updatedAt: '2025-02-10T13:00:00Z',
  },
  {
    id: 'folder-4',
    name: 'School',
    parentId: null,
    userId: 'mock-user-1',
    createdAt: '2025-02-10T14:00:00Z',
    updatedAt: '2025-02-10T14:00:00Z',
  },
  {
    id: 'folder-5',
    name: 'Assignments',
    parentId: 'folder-4',
    userId: 'mock-user-1',
    createdAt: '2025-02-10T14:30:00Z',
    updatedAt: '2025-02-10T14:30:00Z',
  },
  {
    id: 'folder-6',
    name: 'Lectures',
    parentId: 'folder-4',
    userId: 'mock-user-1',
    createdAt: '2025-02-10T15:00:00Z',
    updatedAt: '2025-02-10T15:00:00Z',
  },
  {
    id: 'folder-7',
    name: 'Work',
    parentId: 'folder-3',
    userId: 'mock-user-1',
    createdAt: '2025-02-11T09:00:00Z',
    updatedAt: '2025-02-11T09:00:00Z',
  },
  {
    id: 'folder-8',
    name: 'Personal',
    parentId: 'folder-3',
    userId: 'mock-user-1',
    createdAt: '2025-02-11T10:00:00Z',
    updatedAt: '2025-02-11T10:00:00Z',
  },
];

// Mock files data
export const mockFiles: File[] = [
  {
    id: 'file-1',
    name: 'Project Proposal.pdf',
    type: 'pdf',
    size: 2456789,
    folderId: 'folder-1',
    userId: 'mock-user-1',
    createdAt: '2025-02-12T09:30:00Z',
    updatedAt: '2025-02-12T09:30:00Z',
  },
  {
    id: 'file-2',
    name: 'Meeting Notes.docx',
    type: 'docx',
    size: 1234567,
    folderId: 'folder-1',
    userId: 'mock-user-1',
    createdAt: '2025-02-12T10:45:00Z',
    updatedAt: '2025-02-12T10:45:00Z',
  },
  {
    id: 'file-3',
    name: 'Budget.xlsx',
    type: 'xlsx',
    size: 3456789,
    folderId: 'folder-1',
    userId: 'mock-user-1',
    createdAt: '2025-02-12T11:15:00Z',
    updatedAt: '2025-02-12T11:15:00Z',
  },
  {
    id: 'file-4',
    name: 'Profile Photo.jpg',
    type: 'jpg',
    size: 5678901,
    folderId: 'folder-2',
    userId: 'mock-user-1',
    createdAt: '2025-02-13T14:20:00Z',
    updatedAt: '2025-02-13T14:20:00Z',
  },
  {
    id: 'file-5',
    name: 'Banner.png',
    type: 'png',
    size: 7890123,
    folderId: 'folder-2',
    userId: 'mock-user-1',
    createdAt: '2025-02-13T15:30:00Z',
    updatedAt: '2025-02-13T15:30:00Z',
  },
  {
    id: 'file-6',
    name: 'Final Essay.docx',
    type: 'docx',
    size: 2345678,
    folderId: 'folder-5',
    userId: 'mock-user-1',
    createdAt: '2025-02-14T09:00:00Z',
    updatedAt: '2025-02-14T09:00:00Z',
  },
  {
    id: 'file-7',
    name: 'Data Analysis.xlsx',
    type: 'xlsx',
    size: 3456789,
    folderId: 'folder-5',
    userId: 'mock-user-1',
    createdAt: '2025-02-14T10:15:00Z',
    updatedAt: '2025-02-14T10:15:00Z',
  },
  {
    id: 'file-8',
    name: 'Week 1 Lecture.pdf',
    type: 'pdf',
    size: 4567890,
    folderId: 'folder-6',
    userId: 'mock-user-1',
    createdAt: '2025-02-14T11:30:00Z',
    updatedAt: '2025-02-14T11:30:00Z',
  },
  {
    id: 'file-9',
    name: 'Week 2 Lecture.pdf',
    type: 'pdf',
    size: 5678901,
    folderId: 'folder-6',
    userId: 'mock-user-1',
    createdAt: '2025-02-14T11:45:00Z',
    updatedAt: '2025-02-14T11:45:00Z',
  },
  {
    id: 'file-10',
    name: 'Project Timeline.docx',
    type: 'docx',
    size: 1234567,
    folderId: 'folder-7',
    userId: 'mock-user-1',
    createdAt: '2025-02-15T09:00:00Z',
    updatedAt: '2025-02-15T09:00:00Z',
  },
  {
    id: 'file-11',
    name: 'Client Meeting.pptx',
    type: 'pptx',
    size: 6789012,
    folderId: 'folder-7',
    userId: 'mock-user-1',
    createdAt: '2025-02-15T10:30:00Z',
    updatedAt: '2025-02-15T10:30:00Z',
  },
  {
    id: 'file-12',
    name: 'Research Paper.pdf',
    type: 'pdf',
    size: 7890123,
    folderId: null,
    userId: 'mock-user-1',
    createdAt: '2025-02-15T14:00:00Z',
    updatedAt: '2025-02-15T14:00:00Z',
  },
  {
    id: 'file-13',
    name: 'Resume.pdf',
    type: 'pdf',
    size: 1234567,
    folderId: null,
    userId: 'mock-user-1',
    createdAt: '2025-02-15T15:30:00Z',
    updatedAt: '2025-02-15T15:30:00Z',
  },
  {
    id: 'file-14',
    name: 'Code Sample.js',
    type: 'js',
    size: 234567,
    folderId: 'folder-8',
    userId: 'mock-user-1',
    createdAt: '2025-02-16T09:45:00Z',
    updatedAt: '2025-02-16T09:45:00Z',
  },
  {
    id: 'file-15',
    name: 'Style Guide.css',
    type: 'css',
    size: 345678,
    folderId: 'folder-8',
    userId: 'mock-user-1',
    createdAt: '2025-02-16T10:30:00Z',
    updatedAt: '2025-02-16T10:30:00Z',
  },
];